name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**/Cargo.*"
      - "**.rs"
  pull_request:
    branches:
      - main
    paths:
      - "**/Cargo.*"
      - "**.rs"
  merge_group:
    types: [checks_requested]

jobs:
  checks:
    if: ${{ ! startsWith(github.event.head_commit.message, 'release:') }}
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Check (fmt)
        run: nix develop --command -- cargo fmt --check

      - name: Check (clippy)
        run: nix develop --command -- cargo clippy --no-deps --all-features --workspace -- -D warnings

      - name: Check (clippy, windows)
        run: nix develop --command -- cargo clippy --no-deps --all-features --workspace --target x86_64-pc-windows-gnu -- -D warnings

      - name: Check (docs)
        run: nix develop --command -- cargo doc --no-deps --all-features

      - name: Check (docs, windows)
        run: nix develop --command -- cargo doc --no-deps --all-features --workspace --target x86_64-pc-windows-gnu

  build:
    name: Test and Build
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Test
        run: nix develop --command -- cargo test --all-features
        timeout-minutes: 15

      # the default package does run the tests
      - name: Build
        run: nix build . .#windows .#linux .#deb

      # push the .#default package build result to cachix
      - id: path
        run: echo "PATH=$(readlink result)" >> $GITHUB_OUTPUT
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
        with:
          name: necauqua
          pathsToPush: ${{ steps.path.outputs.PATH }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Finalize artifacts
        run: ./.github/workflows/finalize-artifacts.sh

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: Windows
          path: noita-utility-box.exe
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: Generic Linux
          path: noita-utility-box-linux-generic.tar.gz
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: Debian
          path: noita-utility-box.deb
